// Finance HQ — Unified Data Layer
// Auto-generated by the morning briefing agent at 7:00 ET
// Last updated: 2026-03-27T10:00:00-04:00

export const FINANCE_DATA = {
  meta: {
    updated: "2026-03-27T10:00:00-04:00",
    version: "2.0.0",
    agents_active: 14,
    agents_total: 14,
    risk_level: "ELEVATED" as const,
  },

  markets: {
    regime: "Risk-Off",
    summary:
      "Геополитика + инфляция давят на рисковые активы. ФРС в паузе. Extreme fear в крипте.",

    indices: [
      { name: "S&P 500", value: "5,693", change: -1.74, note: "Ещё -0.5% пре-маркет" },
      { name: "Nasdaq", value: "17,844", change: -2.19, note: "Tech под давлением" },
      { name: "VIX", value: "27.6", change: +9.0, note: "Risk-off режим" },
      { name: "US 10Y", value: "4.41%", change: +0.05, note: "8-мес. максимум" },
    ],

    crypto: [
      { name: "Bitcoin", ticker: "BTC", price: 66587, change24h: -4.1, mcap: "1.32T", note: "Тест $66K поддержки" },
      { name: "Ethereum", ticker: "ETH", price: 2071, change24h: -4.5, mcap: "249B", note: "Тест $2,000 поддержки" },
      { name: "Solana", ticker: "SOL", price: 86.67, change24h: -5.6, mcap: "42B", note: "Alpenglow upgrade" },
      { name: "XRP", ticker: "XRP", price: 2.13, change24h: -3.2, mcap: "124B", note: "Commodity status" },
      { name: "Total Crypto", ticker: "TOTAL", price: null, change24h: -3.1, mcap: "2.42T", note: "" },
    ],

    fearGreed: {
      value: 10,
      label: "EXTREME FEAR",
      daysInExtreme: 46,
      history: [
        { label: "Сейчас", value: 10 },
        { label: "Неделю назад", value: 14 },
        { label: "Месяц назад", value: 25 },
        { label: "COVID Mar 2020", value: 11 },
        { label: "Terra/Luna 2022", value: 6 },
      ],
    },

    commodities: [
      { name: "Золото (XAU)", value: "$4,439", change: -1.1, note: "Откат от исторических пиков" },
      { name: "Нефть Brent", value: "$105.85", change: +2.3, note: "Геополитическая премия" },
      { name: "Нефть WTI", value: "$101.20", change: +2.1, note: "" },
    ],

    macro: {
      fedRate: "3.50-3.75%",
      fedOutlook: "Пауза. Dot plot: макс 1 cut в 2026",
      cpi: "2.4%",
      coreCpi: "2.5%",
      unemployment: "4.4%",
      gdpQ1: "~2.0%",
      recessionProb: "~30%",
      nextCpi: "10 апреля 2026",
      nextFomc: "6-7 мая 2026",
    },

    news: [
      {
        title: "SEC + CFTC признали 16 криптоактивов digital commodities",
        impact: "positive" as const,
        category: "regulation",
        detail: "BTC, ETH, SOL, XRP, DOGE, ADA, AVAX, LINK, DOT, HBAR, LTC, BCH, SHIB, XLM, XTZ, APT — теперь commodities.",
        confidence: 95,
        timeframe: "long-term",
      },
      {
        title: "Goldman Sachs повысил вероятность рецессии до 30%",
        impact: "negative" as const,
        category: "macro",
        detail: "Рост с 25%. Факторы: растущая безработица, замедление GDP, геополитика.",
        confidence: 85,
        timeframe: "medium-term",
      },
      {
        title: "Нефть Brent пробила $105 на фоне ближневосточного конфликта",
        impact: "negative" as const,
        category: "commodities",
        detail: "Рост цен на нефть = инфляционное давление. ФРС не может снижать ставку.",
        confidence: 90,
        timeframe: "short-term",
      },
      {
        title: "Solana Alpenglow — финализация блоков за 100-150ms",
        impact: "positive" as const,
        category: "crypto",
        detail: "Votor + Rotor — новый консенсус. Потенциально увеличит спрос на SOL.",
        confidence: 65,
        timeframe: "medium-term",
      },
      {
        title: "Crypto Fear/Greed Index: 46+ дней в extreme fear",
        impact: "neutral" as const,
        category: "sentiment",
        detail: "Исторически extreme fear предшествует отскоку, но timing непредсказуем.",
        confidence: 70,
        timeframe: "short-term",
      },
    ],
  },

  personal: {
    profile: {
      filingStatus: "Married Filing Jointly",
      state: "TX/FL/WA (no state tax)",
      employment: "Self-employed (1099-NEC)",
      incomeStreams: ["Freelance", "Crypto trading", "Staking", "Stocks/Dividends"],
      cryptoExperience: "Beginner",
      cryptoBudget: "$1,000 - $10,000",
    },

    taxAlert: {
      deadline: "2026-04-15",
      daysLeft: 19,
      estimatedTaxPaid2025: false,
      penaltyLikely: true,
      severity: "CRITICAL" as const,
      checklist: [
        { item: "1099-NEC от всех клиентов", done: false },
        { item: "1099-B / 1099-MISC с крипто-бирж", done: false },
        { item: "1099-DIV от брокера", done: false },
        { item: "Полная история крипто-транзакций", done: false },
        { item: "Бизнес-расходы (home office, софт, оборудование)", done: false },
        { item: "Health insurance premiums", done: false },
        { item: "Retirement contributions (SEP-IRA/Solo 401k)", done: false },
      ],
      deductions: [
        { name: "SE Tax Deduction (50%)", savings: "Автоматически", confidence: 95 },
        { name: "Home Office", savings: "$1,500+", confidence: 90 },
        { name: "Health Insurance", savings: "100% premiums", confidence: 90 },
        { name: "SEP-IRA", savings: "$1K-$15K+", confidence: 90 },
        { name: "Business Expenses", savings: "Variable", confidence: 85 },
        { name: "Tax-Loss Harvesting", savings: "Variable", confidence: 70 },
      ],
    },

    financialHealth: {
      cashFlowStatus: "UNKNOWN",
      emergencyFund: "UNKNOWN",
      debtPressure: "UNKNOWN",
      savingsRate: "UNKNOWN",
      netWorthTrend: "UNKNOWN",
      overallScore: null as number | null,
      note: "Предоставьте данные о доходах, расходах и балансах для полного аудита.",
    },

    risks: [
      { risk: "Tax penalty 2025", prob: "~95%", impact: "High", level: "CRITICAL", mitigation: "File ASAP, найти CPA" },
      { risk: "Крипто-потери (новичок)", prob: "~60%", impact: "Medium", level: "HIGH", mitigation: "DCA, size control, education" },
      { risk: "Нет emergency fund", prob: "Unknown", impact: "High", level: "HIGH", mitigation: "Подтвердить 3-6 мес." },
      { risk: "Геополитика → инфляция", prob: "~70%", impact: "Medium", level: "HIGH", mitigation: "Пересмотр бюджета" },
      { risk: "Рецессия 2026", prob: "~30%", impact: "High", level: "MEDIUM", mitigation: "Cash buffer, diversification" },
      { risk: "Фриланс нестабилен", prob: "Unknown", impact: "Medium", level: "MEDIUM", mitigation: "Диверсификация клиентов" },
    ],

    actions: [
      {
        priority: "P0",
        title: "Налоги 2025 — начать процесс СЕГОДНЯ",
        urgency: "TODAY",
        confidence: 95,
        professional: true,
        steps: ["Найти CPA (self-employment + crypto)", "Собрать все 1099", "Выгрузить крипто-транзакции", "SEP-IRA contribution до 15 апреля"],
      },
      {
        priority: "P1",
        title: "Подтвердить Emergency Fund",
        urgency: "This week",
        confidence: 90,
        professional: false,
        steps: ["Предоставить данные о сбережениях", "Если < 3 мес — не инвестировать в крипто", "Перевести в HYSA (4.5-5% APY)"],
      },
      {
        priority: "P1",
        title: "Предоставить финансовые данные",
        urgency: "This week",
        confidence: 100,
        professional: false,
        steps: ["Доходы (среднее за 3-6 мес)", "Расходы (фиксированные + переменные)", "Балансы всех аккаунтов", "Долги и ставки"],
      },
      {
        priority: "P2",
        title: "Крипто — подготовить DCA-план",
        urgency: "After P0+P1",
        confidence: 80,
        professional: true,
        steps: ["Разбить сумму на 4-8 покупок", "Regulated exchange (Coinbase/Kraken)", "BTC 50-60%, ETH 25-30%, SOL 5-10%"],
      },
      {
        priority: "P3",
        title: "Estimated Tax Q1 2026",
        urgency: "April 15",
        confidence: 95,
        professional: false,
        steps: ["Рассчитать с CPA", "Не повторять ошибку 2025"],
      },
    ],

    agents: [
      { name: "Chief Strategist", icon: "🎖️", status: "active" as const },
      { name: "Personal Finance", icon: "💰", status: "awaiting_data" as const },
      { name: "Portfolio Analyst", icon: "📊", status: "awaiting_data" as const },
      { name: "Macro Economist", icon: "🌍", status: "active" as const },
      { name: "Market Intel", icon: "📰", status: "active" as const },
      { name: "News Monitor", icon: "📡", status: "active" as const },
      { name: "Risk Manager", icon: "⚠️", status: "active" as const },
      { name: "Financial Auditor", icon: "🔍", status: "awaiting_data" as const },
      { name: "Forecasting", icon: "🔮", status: "partial" as const },
      { name: "Tax Analyst", icon: "🏛️", status: "alert" as const },
      { name: "Credit & Debt", icon: "💳", status: "awaiting_data" as const },
      { name: "Cost-of-Living", icon: "🛒", status: "active" as const },
      { name: "Behavioral Finance", icon: "🧠", status: "active" as const },
      { name: "Opportunity Scanner", icon: "🔭", status: "partial" as const },
    ],
  },
} as const;

// SHA-256 hash for private section password
export const PWD_HASH = "f012b02d0e0f47eb78cdc4ffbbb3a10eb0c0225075d7e890feb352fa1d509907";
